apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket
  title: "Criar Bucket S3"
spec:
  owner: team-example
  type: service
  parameters:
    - title: "Região AWS"
      type: string         # <-- precisa ser "string"
      name: region         # <-- nome do parâmetro
      description: "A região AWS onde o Stack CloudFormation será criado"
      default: "us-east-1"
    - title: "Nome do Stack"
      type: string
      name: stackName
      default: "demo-s3-bucket-stack"
    - title: "Nome do Bucket"
      type: string
      name: bucketName
      default: "minha-demo-bucket"

  steps:
    - id: deploy-stack
      name: "Implantando Stack CloudFormation"
      action: "aws:cloudFormationDeploy"
      input:
        region: ${{ parameters.region }}
        stackName: ${{ parameters.stackName }}
        template: |
          ...
        templateParameters:
          BucketName: ${{ parameters.bucketName }}
