apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-s3-bucket-testeee
  title: "Criar Bucket S3 testeee"
spec:
  owner: team-example
  type: service
  parameters:
    - title: "Região AWS"
      type: string         # <-- precisa ser "string"
      name: region         # <-- nome do parâmetro
    - title: "Nome do Stack"
      type: string
      name: stackName
    - title: "Nome do Bucket"
      type: string
      name: bucketName
steps:
    - id: deploy-stack
      name: "Implantando Stack CloudFormation"
      action: "aws:cloudFormationDeploy"
      input:
        region: ${{ parameters.region }}
        stackName: ${{ parameters.stackName }}
        template: |
          AWSTemplateFormatVersion: "2010-09-09"
          Description: "Template para criar um Bucket S3"
          Resources:
            S3Bucket:
              Type: "AWS::S3::Bucket"
              Properties:
                BucketName: !Sub "${BucketName}"

          Parameters:
            BucketName:
              Type: String

          Outputs:
            S3BucketName:
              Description: "Nome do bucket S3"
              Value: !Ref S3Bucket

        templateParameters:
          BucketName: ${{ parameters.bucketName }}
